In [1]:
#Tratamiento de datos
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Exploracion de archivos
import sys
sys.path.append('../')

#Funciones personalizadas
from src import soporte_exploracion as spe

## Carga de datos

In [2]:
df_o = pd.read_csv("../data/raw/songs.csv")

In [3]:
df = df_o.copy()

In [4]:
spe.eda_preliminar(df)

PRIMERAS FILAS DEL DATAFRAME

,id,name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,lyrics,year,genre,popularity,total_artist_followers,avg_artist_popularity,artist_ids,niche_genres
0,0Prct5TDjAnEgIqbxcldY9,!,UNDEN!ABLE,"[""HELLYEAH""]",0.415,0.605,7,-11.157,1,0.0575,0.001160,0.838000,0.471,0.193,100.059,79500,"He said he came from Jamaica,\nhe owned a coup...",2016,Rock,0,769490,52.0,"[""4hxDvVq5t8ebPYPdBl1F9f""]","[""groove metal"", ""metal""]"
1,2ASl4wirkeYm3OWZxXKYuq,!!,Childhood Dreams,"[""Yxngxr1""]",0.788,0.648,7,-9.135,0,0.3150,0.900000,0.000000,0.176,0.287,79.998,114000,"Fuck the bitch, now she running with my kids\n...",2019,Hip-Hop,29,143628,45.0,"[""2jwRHcdgkRhelYEMqndDKe""]",[]
2,5tA3ImW310llKo8EMBj2Ga,!!Noble Stabbings!!,Situationist Comedy,"[""Dillinger Four""]",0.171,0.957,2,-5.749,1,0.1490,0.000029,0.000032,0.330,0.349,175.317,197400,You like to stand on the other side\nPoint and...,2002,Rock,0,36619,35.0,"[""4YAN46l70QV0PGXlMg0iHi""]","[""melodic hardcore"", ""pop punk"", ""punk"", ""skat..."
3,0fROT4kK5oTm8xO8PX6EJF,!I'll Be Back!,!I'll Be Back!,"[""Ril\u00e8s""]",0.823,0.612,1,-7.767,1,0.2480,0.168000,0.000000,0.109,0.688,142.959,178533,"It's been a while, shit, I missed the rehab, p...",2018,Hip-Hop,43,929303,63.0,"[""6pdcQa7by8IKuoVXvgknlI""]","[""french rap""]"
4,1xBFhv5faebv3mmwxx7DnS,!Lost!,!Lost!,"[""Ril\u00e8s""]",0.729,0.552,7,-8.562,0,0.0650,0.183000,0.000000,0.131,0.380,86.103,186197,I would like to give you all my time\nI would ...,2018,Hip-Hop,0,929303,63.0,"[""6pdcQa7by8IKuoVXvgknlI""]","[""french rap""]"

--------
MUESTRA ALEATORIA DE 5 FILAS

,id,name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,lyrics,year,genre,popularity,total_artist_followers,avg_artist_popularity,artist_ids,niche_genres
269168,0CGkdIKWvQsgr3zM25jNa8,Light Switch,Happy Commute,"[""Charlie Puth""]",0.690,0.626,6,-5.693,1,0.3060,0.1050,0.000335,0.0881,0.912,184.009,185681,Yeah\n Why you callin' at 11:30\n When you onl...,2022,Pop,0,25598556,82.0,"[""6VuMaDnrHyPL1p4EHjYLi7""]","[""pop"", ""soft pop""]"
506846,46ZElSzE7eSN5nilNLcg4b,Walkin' the Streets Alone,Long Hard Ride,"[""The Marshall Tucker Band""]",0.488,0.753,4,-7.067,0,0.0295,0.0616,0.000233,0.0794,0.873,139.885,309667,I'm singin' a song 'cause I'm in misery\nSick ...,1976,Rock,0,1130300,62.0,"[""59QxeZBL6k9L4oJBGSyukd""]","[""classic rock"", ""country rock"", ""southern rock""]"
468197,4RMji6HHNshcWJoKYG7psK,The Sky Is Crying,Heartbreakin' Woman,"[""Marva Wright""]",0.588,0.421,0,-11.590,1,0.0253,0.2120,0.013300,0.0682,0.781,82.783,195667,"The sky is crying,\n Can you see the tears rol...",2008,Blues,1,1520,14.0,"[""7122Kwu5YJVy0AryshFC72""]","[""blues"", ""zydeco""]"
463269,6HAprTq1UjADYOSubbESga,The One - Acoustic Piano,The One (Acoustic Piano),"[""Matt Johnson"", ""John Adams""]",0.615,0.156,9,-12.168,1,0.0306,0.9490,0.000000,0.0872,0.297,69.895,224114,Tell me\nTell me that you want me\nAnd I'll be...,2018,Folk,35,112017,54.0,"[""7HXBbxW6YwU8lvgBew2p2A"", ""4LaimQU44rsz2kMWQm...","[""acoustic pop""]"
448223,75m3qM5tQautVSjAOGtdlQ,The Best Of Love,All That Matters,"[""Michael Bolton""]",0.687,0.496,6,-7.358,1,0.0258,0.4310,0.000001,0.0982,0.383,91.160,256534,I've got this somethin' to tell you\n There ai...,1997,Rock,32,2613737,67.0,"[""6YHEMoNPbcheiWS2haGzkn""]","[""soft rock""]"

--------
RESUMEN DE DATOS
Nuestro conjunto de datos presenta un total de 550622 filas y 24 columnas
--------
INFO
Los tipos de las columnas son:

                       tipo_dato
id                           str
name                         str
album_name                   str
artists                      str
danceability             float64
energy                   float64
key                        int64
loudness                 float64
mode                       int64
speechiness              float64
acousticness             float64
instrumentalness         float64
liveness                 float64
valence                  float64
tempo                    float64
duration_ms                int64
lyrics                       str
year                       int64
genre                        str
popularity                 int64
total_artist_followers     int64
avg_artist_popularity    float64
artist_ids                   str
niche_genres                 str

Columnas agrupadas por tipo de dato:
- str: ['id', 'name', 'album_name', 'artists', 'lyrics', 'genre', 'artist_ids', 'niche_genres']
- float64: ['danceability', 'energy', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'avg_artist_popularity']
- int64: ['key', 'mode', 'duration_ms', 'year', 'popularity', 'total_artist_followers']

-----------------


Columnas con posibles valores booleanos (0/1):
Columnas que podrían ser booleanas: ['mode']

-----------------

NULOS
Los nulos que tenemos en el conjunto de datos son:

            count  % nulos
album_name     20    0.004
name            3    0.001

--------
DUPLICADOS
Duplicados considerando la columna 'id': 0
--------
FRECUENCIA CATEGORICAS
ID
id
0Prct5TDjAnEgIqbxcldY9    1
2ASl4wirkeYm3OWZxXKYuq    1
5tA3ImW310llKo8EMBj2Ga    1
0fROT4kK5oTm8xO8PX6EJF    1
1xBFhv5faebv3mmwxx7DnS    1
0gNNToCW3qjabgTyBSjt3H    1
1SCFa6gt3r6juLsIqpdwY3    1
1JrpMwlzPuWgfmGiIBi9QI    1
5PIf0fmKJzgK8jgyqXaHGZ    1
0sZb4GBh64F0FOZzQy6QqV    1
Name: count, dtype: int64
-------
NAME
name
Home           221
Without You    175
Forever        163
Hold On        159
Tonight        149
Stay           145
You            144
Alive          141
Alone          139
Heaven         138
Name: count, dtype: int64
-------
ALBUM_NAME
album_name
Greatest Hits                1958
Gold                          456
Live                          394
Love Songs                    381
Super Hits                    365
The Definitive Collection     341
Anthology                     312
Best Of                       308
The Ultimate Collection       253
The Best Of                   249
Name: count, dtype: int64
-------
ARTISTS
artists
["Grateful Dead"]      1500
["Elvis Presley"]      1455
["Aretha Franklin"]    1112
["Bob Dylan"]           978
["Johnny Cash"]         764
["Fleetwood Mac"]       727
["The Beatles"]         723
["Dolly Parton"]        697
["The Beach Boys"]      675
["Willie Nelson"]       630
Name: count, dtype: int64
-------
LYRICS - Columna de texto larga, se muestra métricas simples
Longitud media de texto: 1268.79
Número de palabras promedio: 250.78
-------
GENRE
genre
Rock          197168
Pop            72539
Electronic     69755
Folk           50843
Country        46076
Hip-Hop        41745
R&B            27337
Jazz           17010
Blues          15976
Classical      12173
Name: count, dtype: int64
-------
ARTIST_IDS
artist_ids
["4TMHGUX5WI7OOm53PqSDAT"]    1500
["43ZHCT0cAZBISjO8DG9PnE"]    1455
["7nwUJBm0HE4ZxD3f5cy5ok"]    1112
["74ASZWbe4lXaubB36ztrGX"]     978
["6kACVPfCOnqzgfEF5ryl0x"]     764
["08GQAI4eElDnROBrJRGE0X"]     727
["3WrFJ7ztbogyGnTHbHJFl2"]     723
["32vWCbZh0xZ4o9gkz4PsEU"]     697
["3oDbviiivRWhXwIE8hxkVV"]     675
["5W5bDNCqJ1jbCgTxDD0Cb3"]     630
Name: count, dtype: int64
-------
NICHE_GENRES
niche_genres
[]                                6099
["musicals"]                      5087
["country"]                       4876
["christmas"]                     3356
["r&b"]                           3240
["classic country", "country"]    2643
["indie folk"]                    2591
["pop punk"]                      2566
["singer-songwriter"]             2445
["death metal", "grindcore"]      2325
Name: count, dtype: int64
-------
ESTADISTICOS NUMERICOS

,count,mean,std,min,25%,50%,75%,max
danceability,550622.0,0.53,0.17,0.05,0.41,0.53,0.65,9.900000e-01
energy,550622.0,0.67,0.25,0.00,0.50,0.72,0.89,1.000000e+00
key,550622.0,5.28,3.56,0.00,2.00,5.00,8.00,1.100000e+01
loudness,550622.0,-7.88,3.86,-44.87,-9.91,-7.04,-5.10,0.000000e+00
mode,550622.0,0.67,0.47,0.00,0.00,1.00,1.00,1.000000e+00
speechiness,550622.0,0.09,0.09,0.02,0.04,0.05,0.09,9.700000e-01
acousticness,550622.0,0.24,0.31,0.00,0.00,0.08,0.43,1.000000e+00
instrumentalness,550622.0,0.11,0.24,0.00,0.00,0.00,0.03,1.000000e+00
liveness,550622.0,0.22,0.20,0.01,0.10,0.14,0.29,1.000000e+00
valence,550622.0,0.46,0.25,0.00,0.26,0.45,0.66,1.000000e+00
tempo,550622.0,122.82,29.45,30.95,99.98,121.73,140.94,2.459400e+02
duration_ms,550622.0,237411.63,95552.73,15027.00,184040.00,223000.00,270783.00,4.995315e+06
year,550622.0,2007.14,13.58,1900.00,2002.00,2010.00,2017.00,2.025000e+03
popularity,550622.0,17.58,17.46,0.00,0.00,14.00,30.00,9.800000e+01
total_artist_followers,550622.0,2533411.33,9227678.11,0.00,55102.25,269383.00,1354562.00,2.951819e+08
avg_artist_popularity,550622.0,48.08,19.15,0.00,35.00,49.00,62.00,1.000000e+02