# Limpieza y Transformación de datos

- id -> Pasar a minusculas
- name -> Pasar a minusculas. Eliminar espacios al principio y al final y caracteres especiales innecesarios.
- album_name -> Pasar a minusculas. Eliminar espacios al principio y al final y caracteres especiales innecesarios. Los nulos dejarlos como Nan.
- artists -> Pasar a minusculas. Convertirlo en una lista de Python y crear columna auxiliar main_artist. Eliminar comillas “” y corchetes []. Tambien hay \ en medio de palabras. Seguramente genere nulos.
- lyrics -> La eliminaria.
- artist_ids -> Pasar a minusculas. Igual convertirlo en lista. Eliminar comillas “” y corchetes []. Seguramente genere nulos
- niche_genres -> Eliminar comillas “” y corchetes []. Convertir el texto en lista. Seguramente genere nulos. Además, veo mas de una categoría para la misma fila. Crear nueva columna n_niche_genres con el número de generos.
- year: podrías crear columna decade = year // 10 * 10 para análisis por décadas
- crear n_artists para poder responder las colaboraciones son mas populares

In [3]:
#Tratamiento de datos
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Exploracion de archivos
import sys
sys.path.append('../')

#Funciones personalizadas
from src import soporte_limpieza as spl

In [4]:
# ============================
# 1. Carga de datos
# ============================

df_o = pd.read_csv("../data/raw/songs.csv")
df = df_o.copy()

In [5]:
# ============================
# 2. Limpieza y transformación
# ============================

df = spl.clean_songs(df)

In [6]:
# ============================
# 3. Validación de la limpieza
# ============================

print(f"Dimensiones: {df.shape}")

print("\nTipos de datos")
display(df.dtypes)

print("\nValores nulos")
display(df.isna().sum()[df.isna().sum() > 0])

print("\nDuplicados por ID")
print(df["id"].duplicated().sum())

print("\nNuevas columnas creadas")
display(
    df[
        [
            "main_artist",
            "n_artists",
            "n_niche_genres",
            "decade",
            "duration_min",
            "popularity_per_million_followers"
        ]
    ].head()
)

print("\nColumnas convertidas a listas")
display(
    df[
        [
            "artists",
            "artist_ids",
            "niche_genres"
        ]
    ].head()
)

Dimensiones: (550622, 29)

Tipos de datos

id                                      str
name                                    str
album_name                              str
artists                              object
danceability                        float64
energy                              float64
key                                   int64
loudness                            float64
mode                                    str
speechiness                         float64
acousticness                        float64
instrumentalness                    float64
liveness                            float64
valence                             float64
tempo                               float64
duration_ms                           int64
year                                  int64
genre                                   str
popularity                            int64
total_artist_followers                int64
avg_artist_popularity               float64
artist_ids                           object
niche_genres                         object
n_artists                             int64
main_artist                             str
n_niche_genres                        int64
decade                                  str
popularity_per_million_followers     object
duration_min                        float64
dtype: object

Valores nulos

name                                 4
album_name                          20
main_artist                          6
popularity_per_million_followers    18
dtype: int64

Duplicados por ID
0

Nuevas columnas creadas

,main_artist,n_artists,n_niche_genres,decade,duration_min,popularity_per_million_followers
0,hellyeah,1,2,2010s,1.32,0.0
1,yxngxr1,1,0,2010s,1.90,201.91
2,dillinger four,1,4,2000s,3.29,0.0
3,rilès,1,1,2010s,2.98,46.27
4,rilès,1,1,2010s,3.10,0.0

Columnas convertidas a listas

,artists,artist_ids,niche_genres
0,[hellyeah],[4hxdvvq5t8ebpypdbl1f9f],"[groove metal, metal]"
1,[yxngxr1],[2jwrhcdgkrhelyemqnddke],[]
2,[dillinger four],[4yan46l70qv0pgxlmg0ihi],"[melodic hardcore, pop punk, punk, skate punk]"
3,[rilès],[6pdcqa7by8ikuovxvgknli],[french rap]
4,[rilès],[6pdcqa7by8ikuovxvgknli],[french rap]

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550622 entries, 0 to 550621
Data columns (total 29 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   id                                550622 non-null  str
 1   name                              550618 non-null  str
 2   album_name                        550602 non-null  str
 3   artists                           550622 non-null  object
 4   danceability                      550622 non-null  float64
 5   energy                            550622 non-null  float64
 6   key                               550622 non-null  int64
 7   loudness                          550622 non-null  float64
 8   mode                              550622 non-null  str
 9   speechiness                       550622 non-null  float64
 10  acousticness                      550622 non-null  float64
 11  instrumentalness                  550622 non-null  float64
 12  liveness                          550622 non-null  float64
 13  valence                           550622 non-null  float64
 14  tempo                             550622 non-null  float64
 15  duration_ms                       550622 non-null  int64
 16  year                              550622 non-null  int64
 17  genre                             550622 non-null  str
 18  popularity                        550622 non-null  int64
 19  total_artist_followers            550622 non-null  int64
 20  avg_artist_popularity             550622 non-null  float64
 21  artist_ids                        550622 non-null  object
 22  niche_genres                      550622 non-null  object
 23  n_artists                         550622 non-null  int64
 24  main_artist                       550616 non-null  str
 25  n_niche_genres                    550622 non-null  int64
 26  decade                            550622 non-null  str
 27  popularity_per_million_followers  550604 non-null  object
 28  duration_min                      550622 non-null  float64
dtypes: float64(11), int64(7), object(4), str(7)
memory usage: 121.8+ MB

In [9]:
# ============================
# 4. Guardar dataset limpio
# ============================

df.to_csv("../data/processed/songs_clean.csv", index=False)