In [1]:
#Tratamiento de datos
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Exploracion de archivos
import sys
sys.path.append('../')

#Funciones personalizadas
from src import soporte_exploracion as spe

## Carga de datos

In [2]:
df_o = pd.read_csv("../data/raw/artists.csv")

In [3]:
df = df_o.copy()

In [4]:
spe.eda_preliminar(df)

PRIMERAS FILAS DEL DATAFRAME

,id,name,followers,popularity,genres,main_genre
0,6YROFUbu5zRCHi2xkir5pk,Brian Hyland,67223,47,[],Pop
1,5tFRohaO5yEsuJxmMnlCO9,Barns Courtney,602647,62,[],Electronic
2,3w1Q754jb31h5CXQCcnLNL,Capcom Sound Team,210392,58,"['japanese vgm', 'soundtrack']",Electronic
3,3oDbviiivRWhXwIE8hxkVV,The Beach Boys,5139194,76,['baroque pop'],Classical
4,60zvRmhQHRxokEB1taAVpN,Beth Malone,1569,29,['musicals'],Classical

--------
MUESTRA ALEATORIA DE 5 FILAS

,id,name,followers,popularity,genres,main_genre
22160,4NsVVzuaZGk4aya8Pyacew,Adam Doleac,100143,51,['country'],Country
52131,4rYjRQtTsRTviFEuFlXryi,The Absence,239,13,['melodic death metal'],Electronic
26312,379IT6Szv0zgnw4xrdu4mu,LADIPOE,1088857,56,"['afrobeats', 'afrobeat', 'afropop', 'alté', '...",R&B
23680,0aF0pIALJDBCfFgqiTaK2g,Keljet,7801,23,"['nu disco', 'indie dance', 'french house', 'f...",Electronic
69625,5QATXPPyP5f3UWtwTc15Y9,Benni Hemm Hemm,1684,17,[],Pop

--------
RESUMEN DE DATOS
Nuestro conjunto de datos presenta un total de 71440 filas y 6 columnas
--------
INFO
Los tipos de las columnas son:

           tipo_dato
id               str
name             str
followers      int64
popularity     int64
genres           str
main_genre       str

Columnas agrupadas por tipo de dato:
- str: ['id', 'name', 'genres', 'main_genre']
- int64: ['followers', 'popularity']

-----------------


Columnas con posibles valores booleanos (0/1):
Columnas que podrían ser booleanas: []

-----------------

NULOS
Los nulos que tenemos en el conjunto de datos son:

      count  % nulos
name      2    0.003

--------
DUPLICADOS
Duplicados considerando la columna 'id': 0
--------
FRECUENCIA CATEGORICAS
ID
id
6YROFUbu5zRCHi2xkir5pk    1
5tFRohaO5yEsuJxmMnlCO9    1
3w1Q754jb31h5CXQCcnLNL    1
3oDbviiivRWhXwIE8hxkVV    1
60zvRmhQHRxokEB1taAVpN    1
4hxDvVq5t8ebPYPdBl1F9f    1
2jwRHcdgkRhelYEMqndDKe    1
07d5etnpjriczFBB8pxmRe    1
50bY8HGxT0SuDgJX3AilTT    1
3hyGGjxu73JuzBa757H6R5    1
Name: count, dtype: int64
-------
NAME
name
Howard Jones    6
Chris Martin    6
Ghost           5
Sebastian       5
Castro          5
Tom Bailey      5
Lukie D         5
Friends         5
Jano            5
JD              5
Name: count, dtype: int64
-------
GENRES
genres
[]                                  19580
['musicals']                         1806
['tropical house']                    413
['trance', 'progressive trance']      396
['black metal']                       312
['k-pop']                             275
['hardstyle']                         254
['vocal jazz']                        228
['underground hip hop']               221
["children's music"]                  216
Name: count, dtype: int64
-------
MAIN_GENRE
main_genre
Electronic    20032
Rock          13867
Pop            8703
Hip-Hop        8097
Folk           5236
Classical      4871
R&B            3312
Country        3095
Jazz           2896
Blues          1331
Name: count, dtype: int64
-------
ESTADISTICOS NUMERICOS

,count,mean,std,min,25%,50%,75%,max
followers,71440.0,233049.03,2204254.64,0.0,912.75,7865.0,45107.5,168508682.0
popularity,71440.0,28.77,18.01,0.0,15.00,28.0,41.0,100.0